# Generated by Django 4.0.4 on 2022-05-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('idarea', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_bodega', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'bodega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CabezaMovimiento',
            fields=[
                ('idcabeza_movimiento', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=45)),
                ('fecha_documento', models.DateField()),
            ],
            options={
                'db_table': 'cabeza_movimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idcargo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=45)),
                ('descripcion_cargo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idcategorias', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuerpoMovimiento',
            fields=[
                ('idcuerpo_movimiento', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'cuerpo_movimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('idkardex', models.IntegerField(primary_key=True, serialize=False)),
                ('stock_actual', models.CharField(max_length=45)),
                ('precio_venta', models.CharField(max_length=45)),
                ('precio_compra', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'kardex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoBodega',
            fields=[
                ('idmovimiento_bodega', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'movimiento_bodega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.IntegerField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=45)),
                ('primer_apellido', models.CharField(max_length=45)),
                ('segundo_apellido', models.CharField(max_length=45)),
                ('gmail', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=12)),
                ('edad', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(db_column='id producto', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=25)),
                ('codigo', models.CharField(max_length=30)),
                ('talla', models.CharField(max_length=4)),
                ('color', models.CharField(max_length=20)),
                ('imagen_producto', models.CharField(max_length=20)),
                ('stock_minimo', models.CharField(max_length=45)),
                ('stock_maximo', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('idtemporada', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'temporada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('idtipo_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMovimientoBodega',
            fields=[
                ('idtipo_movimiento_bodega', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_movimientob', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_movimiento_bodega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipomovimientof',
            fields=[
                ('idtipomovimientof', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_movimientof', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipomovimientof',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('idtipo_persona', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idtipo_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_producto',
                'managed': False,
            },
        ),
    ]
